# Generated by Django 4.0.1 on 2022-01-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
