# Generated by Django 4.0.3 on 2022-03-12 20:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpk_rating', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tpk_description', models.TextField(max_length=500)),
                ('tpk_access_information', models.TextField(default='NA', max_length=500)),
                ('tpk_price_per_hour', models.FloatField(default=2.0)),
                ('tpk_parking_area', models.FloatField()),
                ('tpk_has_features', models.BooleanField(default=False)),
                ('tpk_vehicle_capacity', models.IntegerField()),
                ('tpk_created_on', models.DateTimeField(auto_now_add=True)),
                ('tpk_last_booked', models.DateTimeField()),
                ('tpk_is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpaceFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpk_has_car_charging', models.BooleanField(default=False)),
                ('tpk_has_car_wash', models.BooleanField(default=False)),
                ('tpk_has_indoor_parking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpaceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpk_base64_image', models.TextField(blank=True, null=True)),
                ('tpk_parkingspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpk_parkingspace_images', to='parkingspace.parkingspace')),
            ],
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='tpk_parking_features',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpk_parking_features', to='parkingspace.parkingspacefeatures'),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='tpk_ps_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tpk_ps_location', to='maps.parkermap'),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='tpk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
