# Generated by Django 4.0.1 on 2022-03-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='tpk_ps_name',
            field=models.TextField(blank=True),
        ),
    ]
