export const spaces = [{
    parking_area : 100,
    has_features : true,
    vehicle_capacity : 1,
    name: "Multistorey Car Parking",
    address : "200 University Avenue West",
    city : "Waterloo",
    country : "Canada",
    area_code : "N2L6P1",
    lat : 43.46776431622622,
    long : -80.53847208326658,
    parking_features : {has_car_charging:true, has_car_wash : true, has_indoor_parking : true},
    created_on : new Date(),
    last_booked : new Date(),
    is_booked : true,
    rating : 3,
    description : "Your first arrival must be between Monday-Friday from 9.30 to 17:30!.Convenient parking close to the Central station and Supermarket. From here you can walk to all places in the city centre of Waterloo",
    access_information: "Once you made your reservation, you will receive further details on where to pick up the electronic pass nearby the parking garage.You are able to enter and exit as many times as you want during your reservation period.",
    price: 15,
    images:[]
},{
    parking_area : 100,
    has_features : true,
    vehicle_capacity : 1,
    name: "Parking lot H",
    address : "200 University Avenue West",
    city : "Waterloo",
    country : "Canada",
    area_code : "N2L6P1",
    lat : 43.47407380882113,
    long :  -80.54652068961833,
    parking_features : {has_car_charging:true, has_car_wash : true, has_indoor_parking : true},
    created_on : new Date(),
    last_booked : new Date(),
    is_booked : true,
    rating : 5,
    description : "Your first arrival must be between Monday-Friday from 9.30 to 17:30!.Convenient parking close to the Central station and Supermarket. From here you can walk to all places in the city centre of Waterloo",
    access_information: "Once you made your reservation, you will receive further details on where to pick up the electronic pass nearby the parking garage.You are able to enter and exit as many times as you want during your reservation period.",
    price: 15,
    images:[]
},
{
    parking_area : 100,
    has_features : true,
    vehicle_capacity : 1,
    name: "Parking lot C",
    address : "200 University Avenue West",
    city : "Waterloo",
    country : "Canada",
    area_code : "N2L6P1",
    lat : 43.46953850599665,
    long :  -80.53718471549792,
    parking_features : {has_car_charging:true, has_car_wash : true, has_indoor_parking : true},
    created_on : new Date(),
    last_booked : new Date(),
    is_booked : true,
    rating : 2,
    description : "Your first arrival must be between Monday-Friday from 9.30 to 17:30!.Convenient parking close to the Central station and Supermarket. From here you can walk to all places in the city centre of Waterloo",
    access_information: "Once you made your reservation, you will receive further details on where to pick up the electronic pass nearby the parking garage.You are able to enter and exit as many times as you want during your reservation period.",
    price: 15,
    images:[]
}
];