# Generated by Django 4.0.2 on 2022-03-08 00:23

import apps.booking.models
from django.conf import settings
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkingspace', '__first__'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='BookingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpk_book_start_datetime', models.DateTimeField()),
                ('tpk_book_end_datetime', models.DateTimeField()),
                ('tpk_book_cancelled', models.BooleanField(default=False)),
                ('tpk_booking_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpk_user', to=settings.AUTH_USER_MODEL)),
                ('tpk_parkingspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpk_parkingspace', to='parkingspace.parkingspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookingitems',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('tpk_book_cancelled', False)), expressions=((apps.booking.models.TsTzRange('tpk_book_start_datetime', 'tpk_book_end_datetime', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('tpk_parkingspace', '=')), name='exclude_overlapping_booking'),
        ),
    ]
